apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: quantbox

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - sandbox-deployment.yaml
  - sandbox-service.yaml
  - main-api-deployment.yaml
  - main-api-service.yaml
