apiVersion: v1
kind: Service
metadata:
  name: main-api-service
  namespace: quantbox
spec:
  selector:
    app: main-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080  # External access
  type: NodePort
